[package]
name = "okex-rs"
version = "0.1.0"
authors = ["tnpxu <tanapatxu@gmail.com>"]

[lib]
name = "okex"
path = "src/lib.rs"

[dependencies]
hex = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
error-chain = "0.12"
ring = "0.13.2"
reqwest = "0.8"
tungstenite = "0.6"
url = "1.7"